"""
This module contains constants used in RoofRealEstate.
"""

import os

bot_api = os.environ.get("TG_BOT_API")
REQ_URL = os.environ.get("GET_URL")
categories = {"آپارتمان": "Apartment", "ویلا": "Villa", "زمین": "Land"}
cities = {
    "تهران": "tehran",
    "کرج": "karaj",
    "مشهد": "mashhad",
    "اصفهان": "isfahan",
    "تبریز": "tabriz",
    "شیراز": "shiraz",
    "اهواز": "ahvaz",
    "قم": "qom",
    "کرمانشاه": "kermanshah",
}
districts = {
    "tehran": {
        "ajudaniye": "آجودانیه",
        "niavaran": "نیاوران",
        "kashanak": "کاشانک",
        "jamaran": "جماران",
        "emamzadeh-ghasem": "امامزاده قاسم",
        "golab-darreh": "گلاب‌دره",
        "dar-abad": "درآباد",
        "aqdasiyeh": "عقداصیه",
        "shahrak-naft": "شهرک نفت",
        "shahrak-golha": "شهرک گلها",
        "shahrak-mahallati": "شهرک محلاتی",
        "sohanak": "سوهانک",
        "ozgol": "ازگل",
        "darband": "دربند",
        "velenjak": "ولنجک",
        "zafaraniyeh": "زعفرانیه",
        "evin": "اوین",
        "darakeh": "درکه",
        "farahzad": "فرح‌زاد",
        "mahmoodiyeh": "محمودیه",
        "tajrish": "تجریش",
        "kamraniyeh": "کامرانیه",
        "chizar": "چیذر",
        "farmanieh": "فرمانیه",
        "qeytarieh": "قیطریه",
        "dezashib": "دزاشیب",
        "pasdaran": "پاسداران",
        "ekhtiarieh": "اختیاریه",
        "qolhak": "قلهک",
        "darrous": "دروس",
        "zafar": "ظفر",
        "mirdamad": "میرداماد",
        "saadat-abad": "سعادت‌آباد",
        "shahrak-gharb": "شهرک غرب",
        "vanak-village": "روستای ونک",
        "punak": "پونک",
        "zargandeh": "زرگنده",
        "elahiyeh": "الهیه",
        "jordan": "ژرفا",
        "ararat": "آرارات",
        "gisha": "گیشا",
        "yousef-abad": "یوسف‌آباد",
        "amir-abad": "امیرآباد",
        "baharestan": "بهارستان",
        "bazaar": "بازار",
        "jomhouri": "جمهوری",
        "seyyed-khandan": "سیدخندان",
        "gandhi": "گاندی",
        "hasan-abad": "حسن‌آباد",
        "shian": "شیان",
        "lavizan": "لاویزان",
        "ghanat-kowsar": "قنات کوثر",
        "shemiran-now": "شمیران نو",
        "west-tehran-pars": "غرب تهران‌پارس",
        "east-tehran-pars": "شرق تهران‌پارس",
        "majid-abad": "مجیدآباد",
        "estakhr": "استخر",
        "shahrak-omid": "شهرک امید",
        "oghaf": "اوقاف",
        "university-of-science-and-technology": "دانشگاه علم و صنعت",
        "madaen": "مدائن",
        "dardasht": "دردشت",
        "hafthoz": "هفت‌حوض",
        "fadak": "فدک",
        "hakimiyeh": "حکیمیه",
        "zeynabiyeh": "زینبیه",
        "tehran-now": "تهران نو",
        "shams-abad": "شمس‌آباد",
        "majidiyeh": "مجیدیه",
        "dabestan": "دبستان",
        "kazem_abad": "کاظم‌آباد",
        "heshmatiyeh": "حشمتیه",
        "aramaneh": "آرامانه",
        "nezam_abad": "نظام‌آباد",
        "vahidiyeh": "وحیدیه",
        "niroo_havayi": "نیروهوایی",
        "shahrak_jandarmeri": "شهرک جندرمری",
        "marzdaran": "مرزداران",
        "shahrak_koohsar": "شهرک کوهسار",
        "morad_abad": "مرادآباد",
        "almahdi": "المهدی",
        "north_jannat_abad": "جنت‌آباد شمالی",
        "central_jannat_abad": "جنت‌آباد مرکزی",
        "shahin": "شاهین",
        "south_jannat_abad": "جنت‌آباد جنوبی",
        "north_shahran": "شهران شمالی",
        "south_shahran": "شهران جنوبی",
        "kan": "کان",
        "baharan": "بهاران",
        "shahr_ziba": "شهر زیبا",
        "andisheh": "اندیشه",
        "sazman_aab": "سازمان آب",
        "sazman_barnameh": "سازمان برنامه",
        "shahrak_parvaz": "شهرک پرواز",
        "eram": "ایرام",
        "dehkadeh_olympic": "دهکده المپیک",
        "zibadasht": "زیبادشت",
        "shahrak_sadra": "شهرک صدرا",
        "azadi": "آزادی",
        "shahrak_rahahan": "شهرک راههان",
        "shahrak_ansar": "شهرک انصار",
        "ekbatan": "اکباتان",
        "kuy_bimeh": "کوی بیمه",
        "shahrak_apadana": "شهرک آپادانا",
        "kuy_ferdows": "کوی فردوس",
        "tarasht": "ترشت",
        "sadeghiyeh": "صادقیه",
        "abazar": "آبازار",
        "kuy_mehran": "کوی مهران",
        "shahrak_esteqlal": "شهرک استقلال",
        "tehransar": "تهرانسر",
        "shahrak_darya": "شهرک دریا",
        "shahrak_aseman": "شهرک آسمان",
        "mehrabad_international_airport": "فرودگاه بین‌المللی مهرآباد",
        "kuy_17_shahrivar": "کوی ۱۷ شهریور",
        "shahrak_ferdos": "شهرک فردوس",
        "south_mehr_abad": "مهرآباد جنوبی",
        "shahrak_taleqani": "شهرک طالقانی",
        "khalij_fars": "خلیج فارس",
        "shad_abad": "شادآباد",
        "shahrak_arghavan_emam_khomeyni": "شهرک ارغوان امام خمینی",
        "ebrahimabad": "ابراهیم‌آباد",
        "yaftabad": "یافت‌آباد",
        "shahrak_moslemin": "شهرک مسلمین",
        "shahrak-vali-asr": "شهرک ولی‌عصر",
        "ostad-moein": "استاد معین",
        "jey": "جی",
        "beryanak": "بریانک",
        "azari": "آذری",
        "falah": "فلاح",
        "daryan-no": "دریان‌نو",
        "tehran-villa": "تهران‌ویلا",
        "shahrara": "شهرآرا",
        "towhid": "توحید",
        "jamalzadeh": "جمال‌زاده",
        "sattarkhan": "ستارخان",
        "patrice-lumumba": "پاتریس لومومبا",
        "keshavarz-boulevard": "خیابان کشاورز",
        "university-of-tehran": "دانشگاه تهران",
        "fatemi": "فاطمی",
        "qezel-qaleh": "قزل‌قلعه",
        "mobarak-abad-beheshti": "مبارک‌آباد بهشتی",
        "hasan-abad-baqerfar": "حسن‌آباد باقرفر",
        "bagh-rezvan": "باغ رضوان",
        "karim-abad": "کریم‌آباد",
        "abdol-abad": "عبدال‌آباد",
        "zahir-abad": "ظاهرآباد",
        "deylaman": "دیلمان",
        "javanmard-qasab": "جوانمرد قصاب",
        "mansuriyeh": "منصوریه",
        "dolat-abad": "دولت‌آباد",
        "malekabad": "ملک‌آباد",
        "ali-abad": "علی‌آباد",
        "shahrak-takhti": "شهرک تختی",
        "shoosh": "شوش",
        "shahrak-kyanshahr": "شهرک کیان‌شهر",
        "moshiriyeh": "مشیریه",
        "karevan": "کاروان",
        "masoodieh": "مسعودیه",
        "qasr-firuzeh-do": "قصر فیروزه دو",
        "afsariyeh": "افسریه",
        "yakhchi-abad": "یخچی‌آباد",
        "chaharsad-dastgah": "چهارصد دستگاه",
        "nazi-abad": "نازی‌آباد",
        "khazaneh": "خزانه",
        "bahmanyar": "بهمنیار",
        "khani-abad": "خانی‌آباد",
        "esfandiyari": "اسفندیاری",
        "shahrak-shariati": "شهرک شهریاری",
        "shahrak-aboozar": "شهرک ابوذر",
        "shahrak-sharifi": "شهرک شریفی",
        "nemat-abad": "نعمت‌آباد",
        "shahid-rajaie": "شهید رجایی",
        "bagh-azari": "باغ آذری",
        "javadiyeh": "جوادیه",
        "rumi": "رومی",
        "zehtabi": "زهتابی",
        "vasfenard": "وسفنارد",
        "hashem-abad": "هاشم‌آباد",
        "shahrak-amiralmomenin": "شهرک امیرالمؤمنین",
        "doolab": "دولاب",
        "ahang": "آهنگ",
        "gomrok": "گمرک",
        "amir-bahador": "امیر بهادر",
        "amiriyeh": "امیریه",
        "moniriyeh": "منیریه",
        "sangelaj": "سنگلج",
        "pamenar": "پامنار",
        "sheykh-hadi": "شیخ هادی",
        "meydan-horr": "میدان حر",
        "eskandari": "اسکندری",
        "salsabil": "سلسبیل",
        "darvazeh-shemiran": "دروازه شمیران",
        "khajeh-nasir-tousi": "خواجه نصیر توسی",
        "imam-hossein": "امام حسین",
        "safa": "صفا",
        "sad-dastgah": "صد دستگاه",
        "tehran-delgosha": "تهران دلگشا",
        "aemmeh-ye-athaar": "آمّه‌ی آثار",
        "piroozi": "پیروزی",
        "qasr-firuzeh-yek": "قصر فیروزه یک",
        "behjat-abad": "بهجت‌آباد",
        "iran-shahr": "ایران‌شهر",
        "sanaey": "صنایع",
        "abbas-abad": "عباس‌آباد",
        "arjantin": "آرژانتین",
        "sohrevardi": "سهروردی",
        "chitgar": "چیتگر",
        "shahrak-ghazali": "شهرک غزالی",
        "shahrak-ghazali-cinema": "شهرک غزالی سینما",
        "sarvazad": "سروآباد",
        "navvab": "نوّاب",
        "vanak": "ونک",
        "amaniyeh": "آمانیه",
        "vardavard": "وردآورد",
        "narmak": "نارمک",
        "sharifabad": "شریف‌آباد",
        "qiamdasht": "قیامدشت",
        "azerbaijan": "آذربایجان",
        "meydan-enghelab": "میدان انقلاب",
        "shademan": "شادمان",
        "jeyhoon": "جی‌هون",
        "meydan-valiasr": "میدان ولی‌عصر",
        "abshar-tehran": "آبشار تهران",
        "havanirooz": "هوانیروز",
        "kouhak": "کوهک",
        "shahrak-pasdaran": "شهرک پاسداران",
        "shahrak-farhangian": "شهرک فرهنگیان",
        "fath": "فتح",
        "saeed-abad": "سعیدآباد",
        "sar-asiyab-mehr-abad": "سرآسیاب مهرآباد",
        "shamshiri": "شمشیری",
        "tolid-daroo": "تولید دارو",
        "behdasht": "بهداشت",
        "dolatkhah": "دولت‌خواه",
        "tehran-hesarak": "تهران حصارک",
        "bagh-feyz": "باغ فیض",
        "shahrak-naft-district5": "شهرک نفت (منطقه ۵)",
        "parvaz": "پرواز",
        "kuy-faraz": "کوی فراز",
        "hezarsang": "هزارسنگ",
        "aseman": "آسمان",
        "sepehr": "سپهر",
        "eivanak": "ایوانک",
        "university-of-sharif": "دانشگاه شریف",
        "darya": "دریا",
        "bagh-ferdows": "باغ فردوس",
        "hekmat": "حکمت",
        "shahrak-valfajr": "شهرک ولفجر",
        "jahad": "جهاد",
        "tavanir": "توانیر",
        "nosrat": "نصرت",
        "nejatollahi": "نجات‌اللهی",
        "tehran-khaghani": "تهران خاغانی",
        "bahar": "بهار",
        "niloufar": "نیلوفر",
        "darb-dowom": "درب دوم",
        "qoba": "قبا",
        "hesar-booali": "حصار بوعلی",
        "araj": "آرج",
        "kuy-nobonyad": "کوی نوبنیاد",
        "tehran-kerman": "تهران کرمان",
        "sorkhe-hesar": "سرخه حصار",
        "javadiyeh-tehran-pars": "جوادیه تهران‌پارس",
        "khak-sefid": "خاک سفید",
        "tehran-lashkar": "تهران لشکر",
        "sabalan": "سبلان",
        "ashtiyani": "آشتیانی",
        "hafezie": "حافظیه",
        "tehran-emamat": "تهران امامت",
        "south-narmak": "جنوب نارمک",
        "zarkesh": "زرکش",
        "taslihat": "تسلیحات",
        "east-shareq": "شرق شرق",
        "khaje-nezam-molk": "خواجه نظام‌ملک",
        "tehran-police": "تهران پلیس",
        "tehran-gorgan": "تهران گرگان",
        "qasemabad": "قاسم‌آباد",
        "dehqan": "دهقان",
        "shahid-asadi": "شهید اسدی",
        "zahed-gilani": "زاهد گیلانی",
        "parastar": "پرستار",
        "taxirani": "تاکسیرانی",
        "nabi-akram": "نبی‌اکرم",
        "shiva": "شیوا",
        "shokoofeh": "شکوفه",
        "sarasiab-doolab": "سرآسیاب دولاب",
        "jaberi": "جابری",
        "shahed": "شاهد",
        "saheb-al-zaman": "صاحب‌الزمان",
        "aref": "عارف",
        "mina": "مینا",
        "mesgar-abad": "مسگرآباد",
        "shahadat": "شهادت",
        "safaiye": "صفاییه",
        "ebn-babevayh": "ابن‌بابویه",
        "shahid-avini": "شهید آوینی",
        "sizdah-aban": "سیزده‌آبان",
        "sartakht": "سرتخت",
        "hamzeh-abad": "حمزه‌آباد",
        "firoozabadi": "فیروزآبادی",
        "khani-abad-no": "خانی‌آباد نو",
        "etehad": "اتحاد",
        "tehran-iran": "تهران ایران",
        "abshar": "آبشار",
        "aminhozour": "امین‌حضور",
        "ferdowsi": "فردوسی",
        "qiam": "قیام",
        "sirous": "سیروس",
        "kosar": "کوثر",
        "qalamestan": "قلمستان",
        "salamat": "سلامت",
        "makhsous": "مخصوص",
        "tehran-zanjan": "تهران زنجان",
        "hashemi": "هاشمی",
        "shahid-dastgheyb": "شهید دستغیب",
        "shabiri": "شبیری",
        "soleymani": "سلیمانی",
        "haftchenar": "هفت‌چنار",
        "bolursazi": "بلورسازی",
        "tehran-shandiz": "تهران شاندیز",
        "zamzam": "زمزم",
        "moqadam": "مقدم",
        "tous": "طوس",
        "golchin": "گلچین",
        "jalili": "جلیلی",
        "imam-sajjad": "امام سجاد",
        "bisim": "بی‌سیم",
        "tayeb": "طیب",
        "khavaran": "خاوران",
        "minabi": "مینابی",
        "atabak": "اتابک",
        "abuzar": "ابوذر",
        "imamzadeh-hasan": "امامزاده حسن",
        "bagh-khazaneh": "باغ خزانه",
        "shahid-borujerdi": "شهید بروجردی",
        "heravi": "هروی",
        "tehran-hosein-abad": "تهران حسین‌آباد",
        "east-saleh-abad": "شرق صالح‌آباد",
        "abdollah-abad": "عبدالله‌آباد",
        "tehran-jolfa": "تهران جلفا",
        "dr-hoshyar": "دکتر حشیار",
        "shahrak-shahid-bagheri": "شهرک شهید باقری",
        "chitgar-lake": "چیتگر (دریاچه چیتگر)",
        "shahrak-daneshgahi": "شهرک دانشگاهی",
        "shahrak-daneshgah-tehran": "شهرک دانشگاه تهران",
        "sharif": "شریف",
        "shirazi": "شیرازی",
    },
    "mashhad": {
        "ghasem-abad": "قاسم‌آباد",
        "vakilabad": "وکیل‌آباد",
        "azadshahr": "آزادشهر",
        "hashemiye": "هاشمیه",
        "reza-shahr": "رضاشهر",
        "sajjad-shahr": "سجادشهر",
        "tollab": "طلاب",
        "abutaleb": "ابوطالب",
        "felestin": "فلسطین",
        "ahmadabad": "احمدآباد",
        "rahnamaei": "رهنمایی",
        "kolahdouz": "کلاهدوز",
        "goharshad": "گوهرشاد",
        "faramaz-abbasi": "فرامذعه‌عباسی",
        "south-motahari": "جنوب مطهری",
        "tabarsi": "طبرسی",
        "mosalla": "مصلی",
        "17-shahrivar": "۱۷ شهریور",
        "toroq": "تروق",
        "kuh-sangi": "کوه‌سنگی",
        "beheshti": "بهشتی",
        "sayyad-shirazi": "سیاد شیرازی",
        "nofel-loshato": "نوفل لوشاتو",
        "sanabaad": "سن‌آباد",
        "daneshjoo": "دانشجو",
        "abdol-motalleb": "عبدالمطلب",
        "haft-e-tir": "هفت‌تیر",
        "emam-khomeini": "امام‌خمینی",
        "holy-shrine": "حرم مطهر",
        "meydan-adl-khomeini": "میدان عدل‌خمینی",
        "honarestan": "هنرستان",
        "imam-reza": "امام‌رضا",
        "mousavi-ghoochani": "موسوی قوچانی",
        "torbat-heydariyeh": "تربت حیدریه",
        "kashmar": "کاشمر",
        "zed-square": "میدان زد",
        "elahiyeh-boulevard": "بلوار الهیه",
        "kuy-mahdi": "کوی مهدی",
        "barq-square": "میدان برق",
        "sadi": "سعدی",
        "quchan": "قوچان",
        "east-gaaz": "شرق گاز",
        "janbaz": "جانباز",
        "resalat": "رسالت",
        "toos-boulevard": "بلوار طوس",
        "shahrak-rajayi": "شهرک رجایی",
        "shahrara": "شهرآرا",
        "shahrak-e-niru-ye-havayi": "شهرک نیروی هوایی",
        "shahrak-e-chahar-cheshmeh": "شهرک چهارچشمه",
        "kuy-e-sarafrazan": "کوی سرافرازان",
        "kuy-e-kowsar": "کوی کوثر",
        "ferdowsi-university-of": "دانشگاه فردوسی",
        "Shahrak-e-Taleqani": "شهرک طالقانی",
        "jahedshahr": "جاهدشهر",
        "fareqoltahsilan": "فارق‌التحصیلان",
        "amiriyeh": "امیریه",
        "sattari": "ستاری",
        "sadaf": "صدف",
        "farhang": "فرهنگ",
        "eqbal": "اقبال",
        "mahdiabad": "مهدی‌آباد",
        "hojjat": "حجت",
        "baharan": "بهاران",
        "fadak": "فدک",
        "kuy-e-amiralmomenin": "کوی امیرالمؤمنین",
        "keshavaz": "کشاورز",
        "sepad": "سپاد",
        "bahman": "بهمن",
        "pardis": "پردیس",
        "kuy-e-nane-razavi": "کوی نان‌علی‌رضوی",
        "isargaran": "اسارگران",
        "shafa": "شفا",
        "samarghand": "سمرقند",
        "shahid-honarvar": "شهید هنرور",
        "north-shahid-mottahari": "شمال شهید مطهری",
        "ayatollah-ebadi": "آیت‌الله عبادی",
        "ershad": "ارشاد",
        "majd": "مجد",
        "amel": "عامل",
        "malek-abad-garden": "باغ ملک‌آباد",
        "10-day": "ده‌روزه",
        "rahahan": "رهاهان",
        "iman": "ایمان",
        "koushesh": "کوشش",
        "jannat": "جنت",
        "abkuh": "آبکوه",
        "shahrak-e-hashmenizhad": "شهرک هشم‌نیژاد",
        "fatemiye": "فاطمیه",
        "balal": "بلال",
        "khaje-rabi": "خواجه‌ربیع",
        "kuy-e-daravey": "کوی دراوی",
        "sis-abad": "سیس‌آباد",
        "north-tabars": "شمال تبرس",
        "samen": "سامن",
        "shahid-qorbani": "شهید قربانی",
        "kuy-e-raddeh": "کوی ردده",
        "kuy-e-panj-tan": "کوی پنج‌تن",
        "shahid-avini": "شهید آوینی",
        "kuy-e-amiralmonmenin": "کوی امیرالمؤمنین",
        "abbas-abad": "عباس‌آباد",
        "vahid": "وحید",
        "abouzar": "ابوذر",
        "telgerd": "تلگرد",
        "ansar": "انصار",
        "mooud": "مود",
        "poursina": "پورسینا",
        "bahonar": "بهنار",
        "sajadieh": "سجادیه",
        "isar": "اسار",
        "golshour": "گلشور",
        "mehrabad": "مهرآباد",
        "hoseynabad": "حسین‌آباد",
        "rezaieyeh": "رضاییه",
        "noghan": "نوغان",
        "kuy-e-bala-khiaban": "کوی بالاخیابان",
        "kuy-e-paein-khiaban": "کوی پایین‌خیابان",
        "eidgah": "عیدگاه",
        "ayatollah-khamenei": "آیت‌الله خامنه‌ای",
        "charbagh": "چهارباغ",
        "danesh": "دانش",
        "salam": "سلام",
        "onsori": "انصری",
        "dehnavi": "دهنوی",
        "shahid-maqoul": "شهید معقول",
        "amirabad": "امیرآباد",
        "karmandan-e-dovom": "کارمندان دوم",
        "karmandan-e-aval": "کارمندان اول",
        "chahnou": "چهنو",
        "shiroudi": "شیروودی",
        "kuy-e-karagaran": "کوی کارگران",
        "kuy-e-agha-mostafa-khomeini": "کوی آقا مصطفی خمینی",
        "mohammadabad": "محمدآباد",
        "Shahrak-e-Shirin": "شهرک شیرین",
        "moqadam": "مقدم",
        "parvin-etesami": "پروین اعتصامی",
        "neyzeh": "نیزه",
        "panj-tan-al-e-abba": "پنج‌تن آل‌عبّا",
        "valiasr": "ولی‌عصر",
        "kuy-e-police": "کوی پلیس",
        "Kuy-e-Seyyedi": "کوی سیدی",
        "mashhad-hashemi-nejad-international-airport": "فرودگاه بین‌المللی هاشمی‌نژاد مشهد",
        "enqelab": "انقلاب",
        "baharestan": "بهارستان",
        "shahrak-e-abuzar": "شهرک ابوذر",
        "robat-e-Toroq": "رباط ترق",
        "asgariyeh": "عسگریه",
        "ivan": "ایوان",
        "arvand": "اروند",
        "mashhad-international-exhibition": "نمایشگاه بین‌المللی مشهد",
    },
    "karaj": {
        "gohardasht": "گوهردشت",
        "mehrshahr": "مهرشهر",
        "golshahr": "گلشهر",
        "azimieh": "عظیمیه",
        "shahinvila": "شاهین‌ویلا",
        "mehrvila": "مهر‌ویلا",
        "jahanshahr": "جهان‌شهر",
        "baghestan": "باغستان",
        "andisheh-new-town": "شهرک اندیشه",
        "marlik": "مارلیک",
        "hesarak": "حصارک",
        "mesbah": "مسبح",
        "kamalshahr": "کمال‌شهر",
        "kianmehr": "کیان‌مهر",
        "shahriar-karaj": "شهریار (کرج)",
        "haft-e-tir": "هفت‌تیر",
        "taleghani-karaj": "طالقانی (کرج)",
        "manzariyeh-karaj": "منظریه (کرج)",
        "khorramdasht": "خرمدشت",
        "azadegan": "آزادگان",
        "banafsheh": "بنفشه",
        "dehghanvila": "دهقان‌ویلا",
        "malard": "ملارد",
        "meshkindasht": "مشکین‌دشت",
        "vahdat-town": "شهرک وحدت",
        "shahrak-owj": "شهرک اوج",
        "sasani": "ساسانی",
        "derakhti": "درختی",
        "kuy-zanbaq": "کوی زنبق",
        "kuy-mehr": "کوی مهر",
        "abrisham": "آبریشم",
        "aq-tappeh": "آق‌تپه",
        "asadabad": "اسدآباد",
        "rajababad": "رجب‌آباد",
        "hosseinabad": "حسین‌آباد",
        "ahadabad": "احدآباد",
        "kuy-farhang": "کوی فرهنگ",
        "shabanabad": "شبان‌آباد",
        "malekabad": "ملک‌آباد",
        "akhtarabad": "اخترآباد",
        "shahrak-sohrabiyeh": "شهرک سهرابیه",
        "akhgarabad": "اخگرآباد",
        "raazi-town": "شهرک رازی",
        "shahrak-nahal-va-bazr": "شهرک نهال و بازر",
        "golestan": "گلستان",
        "kuy-bahar": "کوی بهار",
        "akbarabad": "اکبرآباد",
        "shahrak-yas": "شهرک یاس",
        "350-metri": "۳۵۰ متری",
        "golha": "گلها",
        "shahrak-zafar": "شهرک ظفر",
        "shahrak-ostadan": "شهرک استادان",
        "karaj-no": "کرج نو",
        "south-kuy-karmandan": "کوی کارمندان جنوبی",
        "hyderabad": "هیدرآباد",
        "kuy-emamiyeh": "کوی امامیه",
        "aseman-town": "شهرک آسمان",
        "baharestan-industrial-town": "شهرک صنعتی بهارستان",
        "mahmodabad": "محمودآباد",
        "shahrak-ali-ebn-abitaleb": "شهرک علی‌ابن‌ابی‌طالب",
        "north-kuy-karmandan": "کوی کارمندان شمالی",
        "golshahrvila": "گلشهر ویلا",
        "ettehad": "اتحاد",
        "valiasr": "ولی‌عصر",
        "dowlatabad": "دولت‌آباد",
        "esfahaniha": "اسفهانی‌ها",
        "chaharsad-dastgah": "چهارصد دستگاه",
        "shahrake-fahmideh": "شهرک فهمیده",
        "kuy-modarres": "کوی مدرس",
        "kuy-farhangian": "کوی فرهنگیان",
        "shahrak-imam-reza": "شهرک امام رضا",
        "pishahangi": "پیش‌آهنگی",
        "goldasht": "گلدشت",
        "kalak": "کلک",
        "jahan-nama": "جهان‌نما",
        "kalak-no": "کلک نو",
        "shahrak-alborz": "شهرک البرز",
        "mehrshahr-5": "مهرشهر ۵",
        "chaman": "چمن",
        "eslamabad": "اسلام‌آباد",
        "bahar": "بهار",
        "Baraghan": "براغان",
        "samandehi": "سمندی",
        "mehrshahr-2": "مهرشهر ۲",
        "mehrshahr-3": "مهرشهر ۳",
        "mehrshar-1": "مهرشهر ۱",
    },
    "shiraz": {
        "shahrak-golestaan": "شهرک گلستان",
        "moaliabad": "معلی‌آباد",
        "molla-sadra": "ملاصدرا",
        "modarresblvd": "بلوار مدرس",
        "farhang-shahr": "فرهنگ‌شهر",
        "atlasi": "اتلسی",
        "rahmat-boulevard": "بلوار رحمت",
        "tachara": "تچرا",
        "valfajr": "ولفجر",
        "ghasr-dasht": "قصردشت",
        "mianrood": "میانرود",
        "seraj": "سراج",
        "amir-kabir": "امیرکبیر",
        "eram-shiraz": "ارم شیراز",
        "sattar-khan": "ستارخان",
        "kolbeh": "کلبه",
        "fazilat-boulevard": "بلوار فضیلت",
        "zand": "زند",
        "east-ghodoosi": "غدوسی شرقی",
        "west-ghodoosi": "غدوسی غربی",
        "zargari": "زرگری",
        "saadi-cinema": "سینما سعدی",
        "afif-abad": "عفیف‌آباد",
        "shahrak-beheshti": "شهرک بهشتی",
        "shahrak-rokn-abad": "شهرک رکن‌آباد",
        "bani-hashemi": "بنی‌هاشمی",
        "goldasht-hafez": "گلدشت حافظ",
        "shahrak-parvaaz": "شهرک پرواز",
        "edalat-boulevard": "بلوار عدالت",
        "kholde-barin": "خلده‌برین",
        "paygah-havayi": "پایگاه هوایی",
        "fargaz": "فرگاز",
        "jomhoori": "جمهوری",
        "azaadi": "آزادی",
        "shahrak-motahhari": "شهرک مطهری",
        "besat": "بساط",
        "kuy-zahra": "کوی زهرا",
        "ziba-shahr": "زیباشهر",
        "siloo": "سیلو",
        "bagh-e-takht": "باغ تخت",
        "tappeh-telviziyoun": "تپه تلویزیون",
        "chencheneh": "چنچنه",
        "kuy-valiasr": "کوی ولی‌عصر",
        "shahrak-isar": "شهرک ایثار",
        "darvazeh": "دروازه",
        "dinakan": "دینکان",
        "mansoor-abad": "منصورآباد",
        "shahrak-bahonar": "شهرک بهنر",
        "goldasht-mohammadi": "گلدشت محمدی",
        "shahrak-erfan": "شهرک عرفان",
        "goldasht-moaliabad": "گلدشت معلی‌آباد",
        "shahrak-bootan": "شهرک بوتان",
        "javadiyeh": "جوادیه",
        "pardis-town": "شهرک پردیس",
        "arian-town": "شهرک آریان",
        "hossein-abad": "حسین‌آباد",
        "bezin-town": "شهرک بزین",
        "north-shahrak-golestan": "شهرک گلستان شمالی",
        "talkh-e-dash": "تلخ‌دش",
        "kuy-azadi": "کوی آزادی",
        "shah-gholi-beigi": "شاه‌قلی‌بیگی",
        "derki": "درکی",
        "kuy-yas": "کوی یاس",
        "golshan": "گلشن",
        "kuy-ghozat": "کوی قوزات",
        "janbazan": "جانبازان",
        "gouyom": "گویم",
        "fajr-town": "شهرک فجر",
        "dokuhak": "دوکوهک",
        "qasre-qomsheh": "قصر قمشه",
        "shahrak-e-mokhaberat": "شهرک مخابرات",
        "niayesh": "نیایش",
        "mahmoudieh": "محمودیه",
        "shahrak-modares": "شهرک مدرس",
        "shahrak-mahdiabad": "شهرک مهدی‌آباد",
        "farzanegan": "فرزانگان",
        "hoveyzeh": "هویزه",
        "rezvan": "رضوان",
        "farhangian": "فرهنگیان",
        "jamaran": "جماران",
        "ahmad-abad": "احمدآباد",
        "shahrak-imam-hossein": "شهرک امام حسین",
        "sajjadieh": "سجادیه",
        "mahdiyeh": "مهدیه",
        "shahrak-e-shahid-navvab-e-safavi": "شهرک شهید نواب صفوی",
        "shahrak-valiasr": "شهرک ولی‌عصر",
        "mohammadiyeh": "محمدیه",
        "goldasht": "گلدشت",
        "kuy-farhangian": "کوی فرهنگیان",
        "shahrak-golha": "شهرک گلها",
        "vazir-abad": "وزیرآباد",
        "sahl-abad": "سهل‌آباد",
        "ghale-no": "قلعه نو",
        "mehregan": "مهرگان",
        "koshkek": "کشک",
        "mah-firouzan": "ماه‌فیروزان",
        "ali-abad": "علی‌آباد",
        "nasr-abad": "نصرآباد",
        "dastkhezr": "دستخضر",
        "sharif-abad": "شریف‌آباد",
        "pdonak": "پدنک",
        "bonakdaran": "بنکداران",
        "shahrak-nirou-entezamie": "شهرک نیرو انتظامی",
        "deh-pialeh": "ده‌پیاله",
        "sheikh-ali-choupan": "شیخ علی چوپان",
        "lashkari": "لشکری",
        "shiraz-cemetery": "قبرستان شیراز",
        "hojat-abad": "حجت‌آباد",
        "saman": "سامان",
        "shahrak-bargh": "شهرک برق",
        "shahrak-daraie": "شهرک درایی",
        "moslem": "مسلم",
        "maqar": "مقار",
        "ghaleh-shahzadeh-bagom": "قلعه شاهزاده‌باگم",
        "shishehgari": "شیشه‌گری",
        "shahid-bahonar-university": "دانشگاه شهید بهنار",
        "saheb-al-zaman": "ساحب‌الزمان",
        "emam-hosein": "امام حسین",
        "golkoub": "گلکوب",
        "dabbagh-khaneh": "دباغ‌خانه",
        "ghaleh-ghebleh": "قلعه قبله",
        "tondgooyan": "تندگویان",
        "laleh": "لاله",
        "zerehi": "زرهی",
        "abyari": "آبیاری",
        "eslahnejad": "اصلاح‌نژاد",
        "tahavoli": "تهاولی",
        "bazaar": "بازار",
        "god-araban": "گدآرابان",
        "bala-kaft": "بالاکفت",
        "eshagh-beyg": "عشق‌بیگ",
        "ahmadi": "احمدی",
        "lab-e-ab": "لب‌آب",
        "shah-square": "میدان شاه",
        "sar-bagh": "سرباغ",
        "kuy-sang-siah": "کوی سنگ سیاه",
        "darvazeh-kazeroon": "دروازه کازرون",
        "dozak": "دوزک",
        "vesal": "وصال",
        "abiverdi": "آبی‌وردی",
        "chogiah": "چوگیاه",
        "pardis-of-eram": "پردیس ارم",
        "kian-shahr": "کیان‌شهر",
        "sharak-e-sadi": "شهرک سادی",
        "kuy-tollab": "کوی طلاب",
        "saadiyeh": "سعدیه",
        "abunasr": "ابونصر",
        "karandish": "کاراندیش",
        "hafeziyeh": "حافظیه",
        "tal-e-hosseinabad": "طل‌حسین‌آباد",
        "kaftarak": "کفترک",
        "chogha": "چغا",
        "berijestoon": "بریجستون",
        "rahmat-abad": "رحمت‌آباد",
        "khalili": "خلیلی",
        "west-moshir": "مشیر غربی",
        "rishmak": "ریشمک",
        "neshat": "نشاط",
        "mahdi-abad": "مهدی‌آباد",
        "haft-tanan": "هفت‌تنان",
        "koozehgari": "کوزه‌گری",
        "fazl-abad": "فضل‌آباد",
        "abjavar": "آبجوار",
        "saheb-divan": "ساحب‌دیوان",
        "dasht-chenaran": "دشت چناران",
        "mehrab": "مهراب",
        "kimia-villa-complex": "کیمیا ویلا",
        "torkan": "ترکان",
        "sait-edari": "سایت اداری",
        "barbari-terminal": "ترمینال بربری",
        "narenjestan": "نارنجستان",
        "pay-kata": "پای‌کتا",
        "shahid-amiri": "شهید امیری",
    },
    "isfahan": {
        "bid-abad": "بیدآباد",
        "abbas-abad-isfahan": "عباس‌آباد اصفهان",
        "lonban": "لنبان",
        "bozorgmehr": "بزرگمهر",
        "khane-esfahan": "خانه اصفهان",
        "baharestan-isfahan": "بهارستان اصفهان",
        "malek-shahr": "ملک‌شهر",
        "sepahan-shahr": "سپاهان‌شهر",
        "sichan": "سیچان",
        "khomeyni-shahr": "خمینی‌شهر",
        "chaharbagh-khajoo": "چهارباغ خواجو",
        "3nd-moshtagh": "عند مشتاق",
        "jolfa": "جلفا",
        "mardavij": "مرداویج",
        "tiran": "تیران",
        "hasht-behesht": "هشت‌بهشت",
        "zeynabiye": "زینبیه",
        "shahreza": "شهرضا",
        "mobarakeh": "مبارکه",
        "hosein-abad": "حسین‌آباد",
        "zarinshahr": "زرین‌شهر",
        "gaz": "گاز",
        "shahrak-shahid-montazeri": "شهرک شهید منتظری",
        "mahmud-abad": "محمودآباد",
        "amin-abad": "امین‌آباد",
        "isfahan-university-of-technology": "دانشگاه صنعتی اصفهان",
        "dehno": "دهنو",
        "ashegh-abad": "عاشق‌آباد",
        "shahrak-kowsar": "شهرک کوثر",
        "shahrak-mahdieh": "شهرک مهدیه",
        "resalat": "رسالت",
        "babukan": "بابکان",
        "dastgerd-e-qadaadeh": "دستگرد قداده",
        "marchin": "مارچین",
        "lemjir": "لمجیر",
        "naser-khosro": "ناصرخسرو",
        "azadegan": "آزادگان",
        "aqiq": "عقیق",
        "sadaf": "صدف",
        "berelian": "برلیان",
        "negarestan": "نگارستان",
        "valiasr-town": "شهرک ولی‌عصر",
        "shahrak-milad": "شهرک میلاد",
        "shahrak-kaveh": "شهرک کاوه",
        "barazandeh": "برازنده",
        "derak": "درک",
        "eshragh": "اشراق",
        "lale": "لاله",
        "24-metri": "۲۴ متری",
        "toghchi": "توغچی",
        "farvardin": "فروردین",
        "baghoush-khaneh": "باغوش‌خانه",
        "pa-ghalea": "پاقلعه",
        "modarres": "مدرس",
        "shahshahan": "شاهشهان",
        "joubareh": "جوباره",
        "shahishabad": "شهیش‌آباد",
        "dastgerdeh": "دستگرده",
        "afaran": "آفران",
        "mahale-now": "محله نو",
        "gurtan": "گورتان",
        "nazband": "نازبند",
        "bazzar": "بازار",
        "janiran": "جانیران",
        "veldan": "ولدان",
        "soodan": "سودان",
        "mohammad-taher": "محمد طاهر",
        "golbahar": "گلبهار",
        "yazd-abad": "یزدآباد",
        "ahmad-abad": "احمدآباد",
        "ladan": "لادان",
        "golzar": "گلزار",
        "ghale-tabre": "قلعه‌طبر",
        "sheykh-yousef": "شیخ یوسف",
        "mofatteh": "مفتّه",
        "dashtestan": "دشتستان",
        "talar": "تلار",
        "paeen-darvazeh": "پائین دروازه",
        "shahzyed": "شاهزید",
        "bisim": "بیسیم",
        "hamedaniyan": "همدانیان",
        "baharan": "بهاران",
        "roknodowleh": "رکن‌الدوله",
        "farhangian": "فرهنگیان",
        "nourbaran": "نورباران",
        "charkhab": "چرخ‌آب",
        "fath-abad": "فتح‌آباد",
        "elyderan": "الیدران",
        "bishe-habib": "بیشه حبیب",
        "jowzdan": "جوزدان",
        "nazhvan": "نژوان",
        "mehr-abad": "مهرآباد",
        "bazougah": "بازوگاه",
        "shahrestan": "شهرستان",
        "jey-Shir": "جی شیر",
        "marnan": "مرنان",
        "takht-foulad": "تخت‌فولاد",
        "kouleh-parcheh": "کوله‌پرچه",
        "gabr-abad": "گبرآباد",
        "ferdos": "فردوس",
        "kerdabad": "کردآباد",
        "kalman": "کلمان",
        "bagh-ghadir": "باغ قدر",
        "farhangiyan-town": "شهرک فرهنگیان",
        "soltan-abad": "سلطان‌آباد",
        "pozveh": "پزوه",
        "khiadan": "خیادان",
        "shahrak-elahiyeh": "شهرک الهیه",
        "kalmh-khvaran": "کلمه‌خواران",
        "zavan": "زوان",
        "pinart": "پینارت",
        "shahrak-zayandeh": "شهرک زاینده",
        "fizadan": "فیزادان",
        "radan": "رادان",
        "kuy-shahid-keshvari": "کوی شهید کشوری",
        "roshan-dasht": "روشن‌دشت",
        "azar": "آذر",
        "naqshe-jahan": "نقش‌جهان",
        "rehnan": "رهنان",
        "doteflan": "دوتفلان",
        "soffeh": "صفه",
        "shahrak-valiasr": "شهرک ولی‌عصر",
        "amiriyeh": "امیریه",
        "bagh-ziar": "باغ زیار",
        "vahid": "وحید",
        "bagh-daryacheh": "باغ دریاچه",
        "farhang": "فرهنگ",
        "mahmoodiyeh": "محمودیه",
        "sheykh-sadough": "شیخ صدوق",
        "khalaja": "خلجه",
        "sajjadieh": "سجادیه",
        "keshavarzi": "کشاورزی",
        "bagh-ferdows": "باغ فردوس",
        "dastgerd": "دستگرد",
        "ghaemiyeh": "قائمیه",
        "saadat-abad": "سادات‌آباد",
        "azadan": "آزادان",
        "golestan": "گلستان",
        "nasr-abad": "نصرآباد",
        "monarjonban": "منارجنبان",
        "dorcheh": "درچه",
        "zahran": "زهران",
        "javan-e-paein": "جوان پائین",
        "javan-e-bala": "جوان بالا",
        "jarvakan": "جروکان",
        "darb-e-sibeh": "درب سیبه",
        "mahaleh-sofla": "محله سفلی",
        "arghavanieh": "ارغوانیه",
        "sanjavamareh": "سنجاومره",
        "ghale-bertianchi": "قلعه برتیانچی",
        "histan": "هستان",
        "shahid-rajaee": "شهید رجایی",
        "buzan": "بوزان",
        "abr": "ابر",
        "kangaz": "کنگاز",
        "sattar": "ستار",
        "ardaji": "اردجی",
        "khatoonabad": "خاتون‌آباد",
        "sudan-zeinabiyeh": "سودان زینبیه",
        "mohammad-abad": "محمدآباد",
        "oman-samani": "عمان سامانی",
        "ghale-nou": "قلعه نو",
        "raran": "راران",
        "andevan": "اندوان",
        "kian": "کیان",
        "gavart": "گاوارت",
        "haftoon": "هفتون",
        "asgariyeh": "عسگریه",
        "batoun": "باتون",
        "tameh": "تمه",
        "jaber-ansari": "جابر انصاری",
        "golmohammadi": "گل‌محمدی",
        "kuy-golzar": "کوی گلزار",
        "bahram-abad": "بهرام‌آباد",
        "shafagh": "شفق",
        "razmandegan": "رزمندگان",
        "miremad": "میرمد",
        "shahriyar": "شهریار",
        "kesare": "کساره",
        "fardovan": "فردوان",
        "kojan": "کوجان",
        "partman": "پرتمان",
        "bagh-zereshk": "باغ زرشک",
        "aineh-khaneh": "آینه‌خانه",
        "bagh-negar": "باغ نگار",
        "hemat-abad": "همت‌آباد",
        "abshar": "آبشار",
        "kuy-emam": "کوی امام",
        "emam-jafar-sadegh-town": "شهرک امام جعفر صادق",
        "sepahan-lane": "کوچه سپاهان",
        "denart": "دنارت",
        "malek": "ملک",
        "khoram": "خرم",
        "bahar-azadi": "بهار آزادی",
        "jelvan": "جلوان",
        "hesseh": "حسه",
        "shahrak-imam-hossein": "شهرک امام حسین",
        "rahim-abad": "رحیم‌آباد",
        "bagh-fadak": "باغ فدک",
        "dolat-abad": "دولت‌آباد",
    },
    "ahvaz": {
        "kianpars": "کیان‌پارس",
        "golestan": "گلستان",
        "zeitoun-karmandi": "زیتون کارمندی",
        "padadshahr": "پدادشهر",
        "koorosh": "کورش",
        "zeitoun-kargari": "زیتون کارگری",
        "naderi": "نادری",
        "parddis": "پردیس",
        "bahonar": "بهنر",
        "lashkar-ahvaz": "لشکر اهواز",
        "kuy-enghelab": "کوی انقلاب",
        "kian-abad": "کیان‌آباد",
        "baharestan-ahvaz": "بهارستان اهواز",
        "sepidar": "سپیدار",
        "naft": "نفت",
        "shahrak-daneshgaah": "شهرک دانشگاه",
        "amanieh": "امانیه",
        "shahrak-naftt": "شهرک نفت",
        "kian-shahr": "کیان‌شهر",
        "meli-rah": "ملی‌راه",
        "farhang-shahr-ahvaz": "فرهنگ‌شهر اهواز",
        "kuy-mahdis": "کوی مهدیس",
        "kuy-nabovvat": "کوی نبوت",
        "kuy-ramezan": "کوی رمضان",
        "taleghani": "طالقانی",
        "yousefi": "یوسفی",
        "resaalat": "رسالت",
        "moeinzadeh": "معین‌زاده",
        "sad-dastgaah": "صد دستگاه",
        "ziba-shaahr": "زیباشهر",
        "kuy-soltan-manesh": "کوی سلطان‌منش",
        "fooladshahr-ahvaz": "فولادشهر اهواز",
        "ariya-shahr": "آریاشهر",
        "pirozi": "پیروزی",
        "new-side": "ساید نیو",
        "zergan": "زرگان",
        "daghagheleh": "داغقله",
        "sisad-dastgah": "صد دستگاه",
        "lashkar-abad": "لشکرآباد",
        "hasir-abad": "حصیرآباد",
        "south-shariati": "جنوب شهریاری",
        "kuy-alavi": "کوی علوی",
        "kut-abdollah": "کوت‌عبدالله",
        "cantex": "کانتکس",
        "shahrak-aghajari": "شهرک آغاجری",
        "shahrak-hafari": "شهرک حافری",
        "padad-phase2": "پداد فاز ۲",
        "padshahr-phase1": "پدشهر فاز ۱",
        "kuy-modarres": "کوی مدرس",
        "kuy-farhangian": "کوی فرهنگیان",
    },
    "qom": {
        "pardisan-qom": "پردیسان قم",
        "safaeieh": "صفائیه",
        "19-dey": "۱۹ دی",
        "bonyad": "بنیاد",
        "emam": "امام",
        "shahid-sadooqi": "شهید صدوقی",
        "tohid": "توحید",
        "amin-boulevard": "بلوار امین",
        "azadegan": "آزادگان",
        "salarieh": "سالاریه",
        "azar": "آذر",
        "haram": "حرم",
        "dourshahr": "دورشهر",
        "shahrak-qods": "شهرک قدس",
        "jomhoori-eslami": "جمهوری اسلامی",
        "attaran": "آتاران",
        "honarestan-qom": "هنرستان قم",
        "somayeh": "ثمیه",
        "haft-e-tir-qom": "هفت تیر قم",
        "kalhori": "کلهری",
        "safa-shahar": "صفا شهر",
        "ensejam": "انسجام",
        "keyvanfar": "کیوانفر",
        "police": "پلیس",
        "ammar-yasir": "عمار یاسر",
        "payame-noor": "پیام نور",
        "danial": "دانیال",
        "yazdan-shahr": "یزدان شهر",
        "enqelab": "انقلاب",
        "ansar-alhossein": "انصار الحسین",
        "emamzade-ebrahim": "امامزاده ابراهیم",
        "modarres": "مدرس",
        "15-khordad": "۱۵ خرداد",
        "kashani-boulevard": "بلوار کاشانی",
        "shahid-beheshti": "شهید بهشتی",
        "golzar": "گلزار",
    },
    "tabriz": {
        "ghara-aghaj": "قره‌آغاج",
        "khatib": "خطیب",
        "raah-ahan": "راه‌آهن",
        "shahrak-noor": "شهرک‌نور",
        "andisheh": "اندیشه",
        "sahand": "سهند",
        "sahand-phase-1": "سهند فاز ۱",
        "sahand-phase-2": "سهند فاز ۲",
        "sahand-phase-3": "سهند فاز ۳",
        "sahand-phase-4": "سهند فاز ۴",
        "esku": "اسکو",
        "khosroshahr": "خسروشهر",
        "taaleqani": "طالقانی",
        "amir-khiz": "امیرخیز",
        "melal-motahed": "ملل متحد",
        "arm": "ارم",
        "pasdaran": "پاسداران",
        "sarakhab": "سرخاب",
        "mansour": "منصور",
        "maralan": "مارالان",
        "eil-goli": "ائل گولی",
        "zaferanieh": "زعفرانیه",
        "vali-e-asr": "ولیعصر",
        "hokm-abad": "حکم‌آباد",
        "nezam-pezeshki": "نظام پزشکی",
        "ostad-jaafari": "استاد جعفری",
        "abuzar": "ابوذر",
        "bahar": "بهار",
        "kuche-bagh": "کوچه باغ",
        "ghods": "قدس",
        "dr-gharib": "دکتر قریب",
        "resalat": "رسالت",
        "shanbe-ghazan": "شنب غازان",
        "farhang": "فرهنگ",
        "beheshthi": "بهشتی",
        "enqelab": "انقلاب",
        "laleh": "لاله",
        "kuye-laleh": "کوی لاله",
        "ravasan": "رواسان",
        "akhmaqiyeh": "اخماقیه",
        "sardroud": "سردرود",
        "bagh-ma’roof": "باغ معروف",
        "manzariyeh": "منظریه",
        "safir-omid": "سفیر امید",
        "shahrak-razi": "شهرک رازی",
        "saadi": "سعدی",
        "abooriyan": "ابوریحان",
        "terminal": "ترمینال",
        "meydan-mosafir": "میدان مسافر",
        "shahed": "شاهد",
        "daneshgah-e payam noor": "دانشگاه پیام نور",
        "nesf-e rah": "نصف راه",
        "ma’raj": "معراج",
        "chernadab": "چرنداب",
        "sa’eb": "صائب",
        "pastur-e jadid": "پاستور جدید",
        "pastur-e ghadim": "پاستور قدیم",
        "17 shahrivar": "17 شهریور",
        "barun avak": "بارون آواک",
        "barnaava": "بارناوا",
        "ahraab": "اهراب",
        "bagh-e fajr": "باغ فجر",
        "khayyam": "خیام",
        "khiyaban-e emam": "خیابان امام",
        "aabersan": "آبرسان",
        "felkeh-e daneshgah": "فلکه دانشگاه",
        "khiyaban-e azaadi": "خیابان آزادی",
        "daneshgah-e fanni-harfeyi": "دانشگاه فنی حرفه‌ای",
        "daneshgah-e sarasari-e tabriz": "دانشگاه سراسری تبریز",
        "daneshgah-e aazaad": "دانشگاه آزاد",
        "bolvar-e niayesh": "بلوار نیایش",
        "kassa’i": "کسائی",
        "yaadegaar-e emam": "یادگار امام",
        "zamzam": "زمزم",
        "tajalla’i": "تجلائی",
        "vaadi-ye rahmat": "وادی رحمت",
        "sajjadiyeh": "سجادیه",
        "saari zamin": "ساری زمین",
        "farhangiyaan": "فرهنگیان",
        "mirdamad": "میرداماد",
        "danesh": "دانش",
        "park-e sa’eb tabrizi": "پارک صائب تبریزی",
        "raja’i shahr": "رجائی شهر",
        "elahi parast": "الهی پرست",
        "mokhabeeraat": "مخابرات",
        "daadgostari": "دادگستری",
        "shah goli": "شاه گولی",
        "ferdows": "فردوس",
        "baharstan": "بهارستان",
        "kuye farshad": "کوی فرشته",
        "baghcheh baan": "باغچه بان",
        "fath abad": "فتح آباد",
        "bimarstan-e beynolmelali": "بیمارستان بین‌المللی",
        "shaadabaad": "شادآباد",
        "bagh-e ya’qub": "باغ یعقوب",
        "ne’mat abad": "نعمت آباد",
        "baasmanj": "باسمنج",
        "khaavaraan": "خاوران",
        "marzdaraan": "مرزداران",
        "masjed": "مصلی",
        "shamim-e paydari": "شمیم پایداری",
        "yaghchiyan": "یاغچیان",
        "parvaaz": "پرواز",
        "narmak": "نارمک",
        "baghmisheh": "باغمیشه",
        "rashdieh": "رشدیه",
        "fahmideh": "فهمیده",
        "shahriar": "شهریار",
        "baranj": "بارنج",
        "nasr": "نصر",
        "elahiye": "الهیه",
        "vali amr": "ولی امر",
        "yousef abad": "یوسف آباد",
        "abbasi": "عباسی",
        "silab": "سیلاب",
        "sarbaz shahid": "سرباز شهید",
        "ideh li": "ایده لی",
        "douh chi": "دوه چی",
        "shams tabrizi": "شمس تبریزی",
        "etehad": "اتحاد",
        "kowsar": "کوثر",
        "khalil abad": "خلیل آباد",
        "rezvanshahr": "رضوانشهر",
        "jannat": "جنت",
        "park-e banafsheh": "پارک بنفشه",
        "mojahed": "مجاهد",
        "mofateh": "مفتح",
        "tavakkoli": "توکلی",
        "bazaar": "بازار",
        "shahnaz": "شهناز",
        "masjed kabood": "مسجد کبود",
        "meydan-e saat": "میدان ساعت",
        "tarbiat": "تربیت",
        "gojeel": "گجیل",
        "hafiz": "حافظ",
        "stadium-e takhti": "استادیوم تختی",
        "bagh-e shomal": "باغشمال",
        "valaman": "والمان",
        "nober": "نوبر",
        "arg-e ali shah": "ارگ علی شاه",
        "se rah-e amin": "سه راه امین",
        "mahghaghi": "محققی",
        "chai kenar": "چای کنار",
        "jamshid abad": "جمشید آباد",
        "foroudgaah": "فرودگاه",
        "azarbayjan": "آذربایجان",
        "yekkeh tokan": "یکه توکان",
        "29 bahman": "29 بهمن",
        "rahnamayi": "راهنمایی",
        "golshahr": "گلشهر",
        "daneshsara": "دانشسرا",
        "pol-e ghaari": "پل قاری",
        "masjed-e sahib al-amr": "مسجد صاحب الامر",
        "daaraayi": "دارایی",
        "manjam": "منجم",
        "daneshgaah-e allameh amini": "دانشگاه علامه امینی",
        "pol-e sangi": "پل سنگی",
        "park-e shams tabrizi": "پارک شمس تبریزی",
        "rezanjaad": "رضانژاد",
        "seyedlar": "سیدلر",
        "tapli baagh": "تپلی باغ",
        "kolaantar koocheh": "کلانتر کوچه",
        "golgasht": "گلگشت",
        "bimarstan-e shaheed madani": "بیمارستان شهید مدنی",
        "bimarstan-e imam reza": "بیمارستان امام رضا",
        "fodak": "فدک",
        "park-e irancell": "پارک ایرانسل",
        "daneshkaadeh-e daandanpezeshki": "دانشکده داندانپزشکی",
        "golnaar": "گلنار",
        "golha": "گلها",
        "daneshkaadeh-e pezeshki": "دانشکده پزشکی",
        "baghaa’iyyeh": "بقائیه",
        "golbaad": "گلباد",
        "mikhak": "میخک",
        "atlas": "اطلس",
        "shaqaa’eq": "شقایق",
        "aashtaab": "آشتاب",
        "shahr-e ketab": "شهر کتاب",
        "khaaghani": "خاقانی",
        "molla zeinaal": "ملا زینال",
        "esma’il baqaal": "اسماعیل بقال",
        "parvin etesami": "پروین اعتصامی",
        "bilankoo": "بیلانکوه",
        "rob’e rashidi": "ربع رشیدی",
    },
    "kermanshah": {
        "park-e shirin": "پارک شیرین",
        "22 bahman": "22 بهمن",
        "shahrak-e sajjadiyeh": "شهرک سجادیه",
        "shahrak-e basij": "شهرک بسیج",
        "kahriz": "کهریز",
        "berimond": "بریموند",
        "kianshahr": "کیانشهر",
        "moradabad": "مرادآباد",
        "golestan": "گلستان",
        "shahrak-e daadgostari": "شهرک دادگستری",
        "dizel abad": "دیزل آباد",
        "doulat abad": "دولت آباد",
        "sadra": "صدرا",
        "pardis": "پردیس",
        "bolvar-e farhikhtegan": "بلوار فرهیختگان",
        "saadeghiyeh": "صادقیه",
        "sarab-e qanbar": "سراب قنبر",
        "cheshmeh sa’di": "چشمه سعدی",
        "chaavoshan": "چاوشان",
        "cheshmeh sa’id": "چشمه سعید",
        "dargah-e gholamali": "درگه غلامعلی",
        "meloodi": "ملودی",
        "bagh-e maahan": "باغ ماهان",
        "bagh-e mehr villa": "باغ مهر ویلا",
        "tehran dasht": "تهران دشت",
        "kahanz": "کهنز",
        "golha": "گلها",
        "elahiye": "الهیه",
        "darreh daraz": "دره دراز",
        "shahrak-e keshavarzi": "شهرک کشاورزی",
        "valayat phase 2": "ولایت فاز ۲",
        "shahrak-e jaam jam": "شهرک جام جم",
        "sohrabi": "سهرابی",
        "bagh-e golareh": "باغ گلاره",
        "park-e sa’di": "پارک سعدی",
        "bolvar-e shaheed": "بلوار شاهد",
        "shahrak-e najafi": "شهرک نجفی",
        "si metri": "سی متری",
        "bolur-e gol-e sorkh": "بلور گل سرخ",
        "golnaz": "گلناز",
        "shariati": "شریعتی",
        "motahhari": "مطهری",
        "ja’far abad": "جعفر آباد",
        "shahrak-e besat": "شهرک بعثت",
        "sarab-e niloofar": "سراب نیلوفر",
        "daneshjoo": "دانشجو",
        "kaashani": "کاشانی",
        "delgushaa": "دلگشا",
        "kasri": "کسری",
        "khalij-e fars": "خلیج فارس",
        "daneshgaah-e aazaad": "دانشگاه آزاد",
        "mantaghe 4": "منطقه ۴",
        "mantaghe 5": "منطقه ۵",
        "mantaghe 3": "منطقه ۳",
        "mantaghe 1": "منطقه ۱",
        "mantaghe 2": "منطقه ۲",
        "mantaghe 6": "منطقه ۶",
        "mantaghe 7": "منطقه ۷",
        "khiyaaban-e pardis": "خیابان پردیس",
        "bolvar-e shaqaa’eq": "بلوار شقایق",
        "borj-e tondis": "برج تندیس",
        "baam-e pardis": "بام پردیس",
        "paayetakht-e kermanshah": "پایتخت کرمانشاه",
        "te’aatr-e shahr": "تئاتر شهر",
        "aazaadegaan": "آزادگان",
        "modares": "مدرس",
        "haddaad aadel": "حداد عادل",
        "arbaabi": "اربابی",
        "a’zami": "اعظمی",
        "fallaahi": "فلاحی",
        "bolvar-e kaargar": "بلوار کارگر",
        "aazaadi": "آزادی",
        "saleemi": "سلیمی",
        "shaheed amjadiyaan": "شهید امجدیان",
        "mohe’d": "موحد",
        "gol mikhak": "گل میخک",
        "jalili": "جلیلی",
        "navaab safari": "نواب سفری",
        "baagh-e ni": "باغ نی",
        "bolvar-e arshaad": "بلوار ارشاد",
        "bolvar-e emaami": "بلوار امامی",
        "khiyaaban-e safaa": "خیابان صفا",
        "sangar": "سنگر",
        "bolvar-e golrizan": "بلوار گلریزان",
        "sherkat-e naft": "شرکت نفت",
        "park-e shaheed": "پارک شاهد",
        "gaavbandeh": "گاوبنده",
        "bimarstan-e raazi": "بیمارستان رازی",
        "shahrak-e baahonar": "شهرک باهنر",
        "emarat-e mandegaar": "عمارت ماندگار",
        "karnaachi": "کرناچی",
        "mehr va maah": "مهر و ماه",
        "nokaan": "نوکان",
        "zafar": "ظفر",
        "maskan": "مسکن",
        "taagh-e bahaaristaan": "طاق بهارستان",
        "baagh-e abrisham": "باغ ابریشم",
        "takavvar": "تکاور",
        "siyahbid-e sofla": "سیاهبید سفلی",
        "foroudgaah": "فرودگاه",
        "nasr": "نصر",
        "farhangiyaan": "فرهنگیان",
        "kaarmendaan": "کارمندان",
        "taavon": "تعاون",
        "havaaniru": "هوانیرو",
        "jahad": "جهاد",
        "vahdat": "وحدت",
        "mo’allem": "معلم",
        "milad": "میلاد",
    },
}
